[2025-02-22T09:03:48.392+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-22T09:03:48.443+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 6_full_etl_test.load_to_postgres scheduled__2025-02-21T09:00:00+00:00 [queued]>
[2025-02-22T09:03:48.486+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 6_full_etl_test.load_to_postgres scheduled__2025-02-21T09:00:00+00:00 [queued]>
[2025-02-22T09:03:48.487+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-02-22T09:03:48.604+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): load_to_postgres> on 2025-02-21 09:00:00+00:00
[2025-02-22T09:03:48.679+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', '6_full_etl_test', 'load_to_postgres', 'scheduled__2025-02-21T09:00:00+00:00', '--job-id', '603', '--raw', '--subdir', 'DAGS_FOLDER/6_full_etl.py', '--cfg-path', '/tmp/tmpt5hpx6a2']
[2025-02-22T09:03:48.700+0000] {standard_task_runner.py:105} INFO - Job 603: Subtask load_to_postgres
[2025-02-22T09:03:48.706+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=19137) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-22T09:03:48.708+0000] {standard_task_runner.py:72} INFO - Started process 19162 to run task
[2025-02-22T09:03:48.826+0000] {task_command.py:467} INFO - Running <TaskInstance: 6_full_etl_test.load_to_postgres scheduled__2025-02-21T09:00:00+00:00 [running]> on host 5ce81506ad67
[2025-02-22T09:03:49.143+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='faris' AIRFLOW_CTX_DAG_ID='6_full_etl_test' AIRFLOW_CTX_TASK_ID='load_to_postgres' AIRFLOW_CTX_EXECUTION_DATE='2025-02-21T09:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-21T09:00:00+00:00'
[2025-02-22T09:03:49.146+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-22T09:04:46.786+0000] {base.py:84} INFO - Retrieving connection 'docker_postgres'
[2025-02-22T09:05:52.728+0000] {job.py:229} INFO - Heartbeat recovered after 24.73 seconds
[2025-02-22T09:09:18.452+0000] {logging_mixin.py:190} INFO - Data berhasil dimasukkan ke PostgreSQL!
[2025-02-22T09:09:19.134+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-22T09:09:19.156+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-22T09:09:19.158+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=6_full_etl_test, task_id=load_to_postgres, run_id=scheduled__2025-02-21T09:00:00+00:00, execution_date=20250221T090000, start_date=20250222T090348, end_date=20250222T090919
[2025-02-22T09:09:19.591+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-22T09:09:19.671+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-22T09:09:19.677+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
